name: Code Quality Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 mypy isort

      - name: Run Black
        run: black --extend-ignore E1 .

      - name: Run Isort
        run: isort .

      - name: Run Flake8
        run: flake8 --max-line-length 150 .

      - name: Run Mypy
        run: mypy .